Repository whatssub/whatssub-admin, pull requests merged in 2019-07, with the labels that each got.

#1 Config ci
  .circleci/config.yml
  README.md
  package.json
  yarn.lock
Labels: ci, setup

#8 First CLA
  CLA.md
  clabot/.clabot
Labels: documentation

#7 SignIn Page
  CLA.md
  STRINGS.ts
  dist/index.html
  package.json
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/Intro.tsx
  src/components/screen/SignIn.tsx
  src/components/screen/__tests__/Intro.test.tsx
  src/components/screen/__tests__/SignIn.test.tsx
  src/components/screen/__tests__/__snapshots__/Intro.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/SignIn.test.tsx.snap
  yarn.lock
Labels: feature

#9 Feature/main screen
  .gitignore
  STRINGS.ts
  dist/index.html
  package.json
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/Intro.tsx
  src/components/screen/Main/ServiceTable.tsx
  src/components/screen/Main/index.tsx
  src/components/screen/Main/mock.ts
  src/components/screen/__tests__/Intro.test.tsx
  src/components/screen/__tests__/Main.test.tsx
  src/components/screen/__tests__/SignIn.test.tsx
  src/components/screen/__tests__/__snapshots__/Intro.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Main.test.tsx.snap
  src/components/shared/SimpleButton.tsx
  src/theme.ts
  src/types/index.ts
  yarn.lock
Labels: feature
